### PR TITLE
Merge in test automation and split the FIFO and LIFO tests

### PR DESCRIPTION
**Pull request by Tonexus**
If you want to test via the Makefile, make sure to read the README.txt for instructions on how to modify mycode2.c. Prof. Pasquale personally approved the modifications, so it's fine to share them here.

### CODE REVIEW

**Comment by Tonexus** [comment]
In regards to 1, technically, the individual tests will still work without the changes to mycode.c as long as the student manually changes the policy before running the corresponding test. i.e. The student would need to change the policy to FIFO before running t1 and then change the policy to LIFO before running t2. Should I change the README to reflect that?

It's just that if a test is run without manually changing the policy, the result will not match the "Expected Result", which I think may be confusing. Maybe I should modify the tests to check that GetSchedPolicy matches what is being tested.

Also, running `make test` will be guaranteed to fail for one of the tests, since the student gets no chance to change the policy in between the tests.

**Comment by Tonexus** [comment]
Oops I mistyped in my last comment. I meant to say that

>  the individual tests will still work _with_ the changes to mycode2.c

In other words, if the student does not make the changes to mycode2.c, they can still run `make t1` and `make t2` and the tests will run correctly as long as they have the right policy set up.

I still want to leave in the .h files and give the student the option to edit their mycode2.c file, but I will add adaptability throughout that makes things easier for the student to not make changes to the mycode2.c file.

In regards to `make test`, even compiling the all the tests still requires the policy to be changed between compiling t1 and t2, so I will leave that command as is.

**Comment by telwell** [comment]
sounds good. when you push those up ill merge.

**Comment by Tonexus** [comment]
Ok, pushed up the new commit.

**Pull request merged**
